name: Virtnbdbackup CI on ubuntu-latest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - uses: abbbi/github-actions-tune@v1
    - name: Python code format test
      run: |
        sudo pip3 install black==22.3
        black --check .
        black --check virtnbdbackup
        black --check virtnbdrestore
        black --check virtnbdmap
        black --check virtnbd-nbdkit-plugin
    - name: Set up ssh access to localhost
      run: |
        sudo ssh-keygen -f /root/.ssh/id_rsa -N ""
        sudo cat /root/.ssh/id_rsa.pub | sudo tee -a /root/.ssh/authorized_keys
        sudo ssh-keyscan -H localhost | sudo tee -a /root/.ssh/known_hosts
    - name: Set up libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          apparmor-profiles \
          bridge-utils \
          dnsmasq-base \
          ebtables \
          libarchive-tools \
          libguestfs-tools \
          libvirt-clients \
          libvirt-daemon \
          libvirt-daemon-system \
          qemu-kvm \
          qemu-utils \
          python3-libnbd \
          python3-tqdm \
          python3-lz4 \
          python3-libvirt \
          python3-lxml \
          python3-paramiko\
          python3-scp \
          nbdkit \
          nbdkit-plugin-python \
          unzip \
          libnbd-bin \
        ;
        # start daemon
        echo 'security_driver = "none"' | sudo tee -a /etc/libvirt/qemu.conf
        sudo aa-teardown
        sudo rm -f /etc/apparmor.d/libvirt/libvirt*
        sudo systemctl start libvirtd
        sudo systemctl restart libvirtd
        sudo modprobe nbd max_partitions=10
    - name: Execute tests (vm1)
      run: cd t && sudo -E make vm1.tests && cd -
    - name: Execute tests (vm3)
      run: cd t && sudo -E make vm3.tests && cd -
    - name: Execute tests (vm4)
      run: cd t && sudo -E make vm4.tests && cd -
    - name: Perform installation
      run: sudo python3 setup.py install
    - name: Execute commands
      run: virtnbdbackup -h && virtnbdrestore -h
