name: Virtnbdbackup CI on ubuntu-latest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: abbbi/github-actions-tune@v1
    - name: Python code format test
      run: |
        sudo pip3 install black==22.1.0
        black --check .
        black --check virtnbdbackup
        black --check virtnbdrestore
        black --check virtnbdmap
        black --check virtnbd-nbdkit-plugin
    - name: Set up libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          apparmor-profiles \
          bridge-utils \
          dnsmasq-base \
          ebtables \
          libarchive-tools \
          libguestfs-tools \
          libvirt-clients \
          libvirt-daemon \
          libvirt-daemon-system \
          qemu-kvm \
          qemu-utils \
          python3-libnbd \
          python3-tqdm \
          python3-lz4 \
          python3-libvirt \
          nbdkit \
          nbdkit-plugin-python \
          unzip \
          libnbd-bin
        ;
        # start daemon
        echo 'security_driver = "none"' | sudo tee -a /etc/libvirt/qemu.conf
        sudo aa-teardown
        sudo rm -f /etc/apparmor.d/libvirt/libvirt*
        sudo systemctl start libvirtd
        sudo systemctl restart libvirtd
        sudo modprobe nbd max_partitions=10
    - name: Update libnbd and python3-libnbd
      run: |
        # ubuntu 20.x does only include libnbd 1.2.2 which is too old
        # update package for ci testing to newer version backported.
        wget https://abbbi.github.io/files/libnbd0_1.6.2-1_amd64.deb
        wget https://abbbi.github.io/files/python3-libnbd_1.6.2-1_amd64.deb
        sudo dpkg -i libnbd0_1.6.2-1_amd64.deb
        sudo dpkg -i python3-libnbd_1.6.2-1_amd64.deb
    - name: Execute tests (vm1)
      run: cd t && sudo -E make vm1.tests && cd -
    - name: Execute tests (vm3)
      run: cd t && sudo -E make vm3.tests && cd -
    - name: Execute tests (vm4)
      run: cd t && sudo -E make vm4.tests && cd -
    - name: Perform installation
      run: sudo python3 setup.py install
    - name: Execute commands
      run: virtnbdbackup -h && virtnbdrestore -h
